# Problem 2
# 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.
#


second_last = 1
last = 2
sum = 0

while True:

	# check if the latest fibonachi-number is an even number
	if last%2==0:
		sum += last
	
	# find the next fibonachi-number
	x = second_last + last
	
	# break if it exceeds four million 
	if x > 4000000:
		break
	
	# update our variables
	temporary_last = last
	last = x
	second_last = temporary_last 

print "Problem 1:",sum